### ISSUE TITLE
Move Page Title from behind gear on About Us Page

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Theme#28]
![image](https://cloud.githubusercontent.com/assets/8271108/15487950/616e95b8-211f-11e6-8524-db90bffcb777.png)

**Comment by joelworsham** [comment]
It seems like a deeper issue here. Like JS is not loading for you. That background should turn blue and the about us title should move to the left.

**Comment by BigActual** [comment]
Working fine now.

**Comment by BigActual** [comment]
You could see the same issue in Eric's screen capture at the top of #25 so it had to be something other than local.

**Comment by d4mation** [comment]
I'm thinking that it was related to 390fcfa where some broken JavaScript was preventing most things on the page from loading correctly. 

I just checked Live, Staging, and my Local install and it looks like the background color and the title are loading correctly now. Looks like this may have been a caching issue since it is working for you now.

**Comment by joelworsham** [comment]
Right, @BigActual probably only just did a manual refresh. (possibly)

**Comment by BigActual** [comment]
Ctrl + F5 all the way.
