### ISSUE TITLE
Stuck updates

### ISSUE THREAD

**Issue by BigActual** [realbig/rbm-theme#53]
https://realbigmarketing.com/wp-admin/network/update-core.php
![image](https://user-images.githubusercontent.com/8271108/151273429-1b44b4c6-9309-478f-aa4d-1b3a1453fb47.png)

**Comment by d4mation** [comment]
Yeah, I have noticed this too. Not sure what exactly is causing it. I've updated this theme a couple times and each time it recognizes that the latest version has updated, so I don't think it is a updates cache issue. It appears to only impact this particular theme.

**Comment by d4mation** [comment]
Figured it out.

There is a Theme in place called "Real Big Marketing (BETA)" that was previously set up and it has an older version string but references the same GitHub Repo. This caused it to show an update for the Theme that's actually in place (since it uses this same Repo) even though the versions are the same.

Seems to be an edge case with Git Updater. In most normal circumstances you would not have the same GitHub Theme URI set for two different Themes.

For the time being I edited the GitHub Theme URI of the offending theme to prevent this from happening in the future.
